/RMG/Manager/Logging/LogLevel summary

/RMG/Geometry/RegisterDetector Scintillator atmospheric_argon 001
/RMG/Geometry/RegisterDetector Scintillator underground_argon 002

/run/initialize

/RMG/Generator/Confine Volume

#/RMG/Generator/Confinement/Physical/AddVolume atmospheric_argon
#/RMG/Generator/Confinement/Physical/AddVolume underground_argon
#/RMG/Generator/Confinement/Physical/AddVolume reentrance_tube

#/RMG/Generator/Confinement/Physical/AddVolume wls_tetratex
/RMG/Generator/Confinement/Physical/AddVolume tpb_coating

#/RMG/Generator/Confinement/Physical/AddVolume wls_inner_coating
#/RMG/Generator/Confinement/Physical/AddVolume wls_tetratex_inner

#/RMG/Generator/Confinement/Physical/AddVolume ofhc_cu
#/RMG/Generator/Confinement/Physical/AddVolume ss_316l


# Increase max iterations for vertex sampling
/RMG/Generator/Confinement/MaxSamplingTrials 1000000


/RMG/Generator/Select GPS
/gps/particle ion
/gps/energy 0 eV
/gps/ion 19 40

/run/beamOn 1000000
